# Generated by Django 4.2.4 on 2023-09-08 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_review_game_game_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.game'),
        ),
    ]
