# Generated by Django 4.2.4 on 2023-09-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_game_review_review_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='games', to='blog.review'),
        ),
    ]
