# Generated by Django 4.2.4 on 2023-09-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_game_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_game', models.TextField(help_text='Write your game to request for review', max_length=100)),
            ],
        ),
    ]
