# Generated by Django 4.2.4 on 2023-09-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_reviewrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(help_text='Enter your review here.', max_length=5000),
        ),
        migrations.AlterField(
            model_name='reviewrequest',
            name='request_game',
            field=models.TextField(max_length=100),
        ),
    ]
