# Generated by Django 4.2.4 on 2023-09-14 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_review_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='type',
            new_name='genre_type',
        ),
    ]
